name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GOOGLE_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev/birdie-org/birdie
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Publish image
        run: |
          make image/publish version=latest
          make image/publish
